# Generated by Django 5.0.6 on 2024-07-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatpdf', '0004_remove_chatgroup_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
    ]
